---
- name: Setup Victorialogs service
  hosts: vlogs-host
  become: true



  tasks:
    - name: Create victorialogs group
      ansible.builtin.group:
        name: "{{ victorialogs_group }}"
        system: yes

    - name: Create victorialogs user
      ansible.builtin.user:
        name: "{{ victorialogs_user }}"
        system: yes
        group: "{{ victorialogs_group }}"
        home: /nonexistent
        shell: /bin/false
        create_home: no

    - name: Download victoria-logs tar.gz
      ansible.builtin.get_url:
        url: "https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ victorialogs_version }}-victorialogs/victoria-logs-linux-amd64-v{{ victorialogs_version }}-victorialogs.tar.gz"
        dest: "/tmp/victoria-logs-linux-amd64-v{{ victorialogs_version }}-victorialogs.tar.gz"

    - name: Extract victoria-logs tar.gz
      ansible.builtin.unarchive:
        src: "/tmp/victoria-logs-linux-amd64-v{{ victorialogs_version }}-victorialogs.tar.gz"
        dest: "{{ victorialogs_install_dir }}"
        remote_src: yes

    - name: Ensure victoria-logs binary is executable
      ansible.builtin.file:
        path: "{{ victorialogs_install_dir }}/victoria-logs-prod"
        mode: '0755'

    - name: Create victorialogs service file from template
      ansible.builtin.template:
        src: templates/vlogs-systemd.j2
        dest: "{{ victorialogs_service_file }}"

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable victorialogs service
      ansible.builtin.systemd:
        name: victorialogs
        enabled: yes

    - name: Start victorialogs service
      ansible.builtin.systemd:
        name: victorialogs
        state: started

    - name: Change ownership of log storage
      ansible.builtin.file:
        path: "{{ victorialogs_storage_path }}"
        owner: "{{ victorialogs_user }}"
        group: "{{ victorialogs_group }}"
        recurse: yes

  handlers:
    - name: restart victorialogs
      ansible.builtin.systemd:
        name: victorialogs
        state: restarted
        enabled: yes