---
- name: Install promtail
  hosts: loki-host
  become: yes
  vars:
    promtail_version: 3.0.0

  tasks:

    - name: Install unzip package
      ansible.builtin.package:
        name: unzip
        state: present

    - name: Download Promtail binary
      ansible.builtin.get_url:
        url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-amd64.zip"
        dest: /usr/local/bin/promtail-linux-amd64.zip

    - name: Unzip promtail binary
      ansible.builtin.unarchive:
        src: /usr/local/bin/promtail-linux-amd64.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Set executable permission on promtail binary
      ansible.builtin.file:
        path: /usr/local/bin/promtail-linux-amd64
        mode: '0755'

    - name: Promtail config file
      ansible.builtin.template:
        src: loki-promtail-config.j2
        dest: /usr/local/bin/config-promtail.yml


    - name: Create promtail user
      ansible.builtin.user:
        name: promtail
        system: yes

    - name: Add promtail user to adm group
      ansible.builtin.user:
        name: promtail
        groups: adm
        append: yes

    - name: Create systemd service file for promtail
      ansible.builtin.template:
        src: promtail-systemd.j2
        dest: /etc/systemd/system/promtail.service
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start promtail service
      ansible.builtin.systemd:
        name: promtail
        enabled: yes
        state: restarted
    