---
- name: Install Netdata On-Prem Version
  hosts: vlogs-host, loki-host
  become: yes
  tasks:
    - name: Install wget
      apt:
        name: wget
        state: present
        update_cache: yes

    - name: Download Netdata kickstart script
      get_url:
        url: https://get.netdata.cloud/kickstart.sh
        dest: /tmp/netdata-kickstart.sh
        mode: '0755'

    - name: Prepare for offline install
      shell: bash /tmp/netdata-kickstart.sh 

    - name: Enable and start Netdata service
      systemd:
        name: netdata
        enabled: yes
        state: started
